name: 🐞 Bug Report
description: File a bug report
title: "Bug: "
labels: ["🛠 goal: fix", "🚦status: awaiting triage", "💻 aspect: code"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Add descriptions
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      placeholder: Add screenshots
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS (Intel)
        - MacOS (Silicon)
        - Chromium
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/taedmonds/lightts/issues)
          required: true